# Generated by Django 2.2.24 on 2023-01-31 11:48
import phonenumbers
from django.db import migrations


def normalize_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(owner_pure_phone):
            flat.owner_pure_phone = owner_pure_phone
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners_pure_phonenumber = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone, move_backward),
    ]
