# Generated by Django 2.2.24 on 2023-01-11 10:29
import phonenumbers
from django.db import migrations


def normalized_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner_pure_phone=phonenumbers.parse(flat.owners_phonenumber, "RU")
        flat.owner_pure_phone = owner_pure_phone
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230111_1255'),
    ]

    operations = [
        migrations.RunPython(normalized_phone),
    ]
