# Generated by Django 2.2.24 on 2023-02-01 08:35

from django.db import migrations


def move_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners.iterator():
        owner.flats.set(Flat.objects.filter(owner=owner.name, owners_phonenumber=owner.phonenumber))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20230201_1210'),
    ]

    operations = [
        migrations.RunPython(move_owners)
    ]
